package com.example.walrusevents;

import static androidx.test.espresso.Espresso.onView;
import static androidx.test.espresso.assertion.ViewAssertions.matches;
import static androidx.test.espresso.matcher.ViewMatchers.isDisplayed;
import static androidx.test.espresso.matcher.ViewMatchers.withId;
import static org.hamcrest.Matchers.not;

import android.os.Bundle;
import androidx.fragment.app.testing.FragmentScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import com.example.walrusevents.R;
import com.example.walrusevents.ui.EventPosterFragment;

import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * This test was generated by Gemini 3, Google DeepMind
 * Fed in the data related classes and the poster/qr code related fragment and asked it for a test
 * to see if the fragment displays the poster correct and if there is no image found if the
 * "no image found" image is displayed
 * 11/03/26
 */
@RunWith(AndroidJUnit4.class)
public class EventPosterFragmentTest {

    @Test
    public void testFragmentUILoadingCycle() {
        // 1. Create the arguments (mimicking the QR scan data)
        Bundle args = new Bundle();
        args.putString("event_id", "test_poster");

        // 2. Launch the fragment in isolation
        FragmentScenario<EventPosterFragment> scenario =
                FragmentScenario.launchInContainer(EventPosterFragment.class, args);

        // 3. Check that the ImageView exists and is visible
        onView(withId(R.id.eventPosterImage)).check(matches(isDisplayed()));

        // 4. Since Firebase is async, we wait a few seconds for the load to finish
        try {
            Thread.sleep(5000); // 5 seconds for the network call
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // 5. VERIFY: The progress bar should be GONE now
        onView(withId(R.id.posterProgressBar)).check(matches(not(isDisplayed())));
    }

    @Test
    public void testErrorImageShowsOnInvalidId() {
        Bundle args = new Bundle();
        args.putString("event_id", "invalid_id_123");

        FragmentScenario.launchInContainer(EventPosterFragment.class, args);

        // Wait for the failure to trigger
        try { Thread.sleep(3000); } catch (InterruptedException e) {}

        // Verify the ProgressBar is hidden
        onView(withId(R.id.posterProgressBar)).check(matches(not(isDisplayed())));

        // Check that the ImageView is still displayed (it will be holding your error drawable)
        onView(withId(R.id.eventPosterImage)).check(matches(isDisplayed()));
    }
}
