package com.example.walrusevents;

import android.graphics.Bitmap;

import androidx.test.ext.junit.runners.AndroidJUnit4;

import com.example.walrusevents.controllers.OEventDetailsController;
import com.example.walrusevents.data.FirebaseAPIManager;
import com.example.walrusevents.model.Event;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

/**
 * Integration test for Firebase Image Storage.
 * Verifies that a generated event poster can be successfully uploaded to Firebase.
 * This test was generated by Gemini 3, Google DeepMind
 * Fed in context for FireBase image storage testing
 * 06/04/26
 */
@RunWith(AndroidJUnit4.class)
public class FirebaseImageStorageTest {

    @Test
    public void testEventPosterUpload() throws InterruptedException {
        // 1. Setup
        // Ensure eventId is unique to avoid permission/collision issues during parallel tests
        String uniqueEventId = "test-" + System.currentTimeMillis();
        Event testEvent = new Event("Integration Test Party", uniqueEventId, "test-owner");
        testEvent.setDescription("Testing Firebase Image Storage Upload");
        
        OEventDetailsController controller = new OEventDetailsController(testEvent);
        CountDownLatch latch = new CountDownLatch(1);

        // 2. Execution
        // This generates both QR and Poster bitmaps internally and sets them on the model
        controller.generateQRAndPoster();
        Bitmap poster = controller.getPoster();

        Assert.assertNotNull("Generated poster should not be null", poster);

        FirebaseAPIManager apiMgr = new FirebaseAPIManager();

        // 3. Validation
        // We use the unique event ID as the filename to ensure we can write to this path
        String fileName = "integration_test_poster_" + uniqueEventId;
        
        apiMgr.uploadBitmap(poster, fileName, new FirebaseAPIManager.OnUploadCompleteListener() {
            @Override
            public void onSuccess() {
                latch.countDown();
            }

            @Override
            public void onFailure(String error) {
                Assert.fail("Upload failed: " + error);
                latch.countDown();
            }
        });

        // Wait up to 20 seconds for the network to finish (Firebase can be slow on CI/Emulators)
        boolean success = latch.await(20, TimeUnit.SECONDS);
        Assert.assertTrue("The upload timed out after 20 seconds", success);
    }
}
