package com.example.walrusevents;

import androidx.test.ext.junit.runners.AndroidJUnit4;

import com.example.walrusevents.data.NotificationRepository;
import com.example.walrusevents.model.Notification;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

/**
 * Integration test for the notification system.
 * This test uses only existing public methods from NotificationRepository.
 * This test was generated by Gemini 3, Google DeepMind
 * Fed in the context for notification testing
 * 06/04/26
 */
@RunWith(AndroidJUnit4.class)
public class NotificationIntegrationTest {

    private NotificationRepository notificationRepo;

    @Before
    public void setUp() {
        notificationRepo = new NotificationRepository();
    }

    @Test
    public void testNotificationRoundTrip() throws InterruptedException {
        // Use a unique ID to avoid interference with other tests or real data
        String testUserId = "test_user_" + System.currentTimeMillis();
        String testTitle = "Integration Test Title";
        String testMessage = "This is a test message for the notification system.";
        String testEventId = "test-event-123";
        
        Notification testNotification = new Notification(
                testTitle, 
                testMessage, 
                testEventId, 
                Notification.NotificationTarget.ALL
        );

        // 1. Send the notification
        notificationRepo.sendNotificationToUser(testUserId, testNotification);

        // 2. Retrieve the notification and verify
        final boolean[] verified = {false};

        // Poll or wait a bit for Firestore to propagate the write
        long startTime = System.currentTimeMillis();
        while (System.currentTimeMillis() - startTime < 15000) { // 15 second timeout
            CountDownLatch innerLatch = new CountDownLatch(1);
            notificationRepo.getNotificationsForUser(testUserId, querySnapshot -> {
                if (querySnapshot != null) {
                    List<Notification> notifications = querySnapshot.toObjects(Notification.class);
                    if (!notifications.isEmpty()) {
                        Notification received = notifications.get(0);
                        if (testTitle.equals(received.getTitle()) && 
                            testMessage.equals(received.getMessage()) &&
                            testEventId.equals(received.getEventId())) {
                            verified[0] = true;
                        }
                    }
                }
                innerLatch.countDown();
            });
            
            innerLatch.await(3, TimeUnit.SECONDS);
            if (verified[0]) break;
            Thread.sleep(1000); // Wait before retrying
        }

        Assert.assertTrue("Notification was not correctly retrieved from Firebase within timeout", verified[0]);
    }
}
