package com.example.walrusevents;

import static org.junit.Assert.*;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import com.example.walrusevents.data.FirebaseAPIManager;
import com.example.walrusevents.data.ImageRepository;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

/**
 * This test was generated by Gemini 3, Google DeepMind
 * Fed in the data related classes and the poster/qr code related fragment and asked it for a test
 * for a successful image retrieval and one for an image that doesn't exit on Firebase
 * 11/03/26
 */
@RunWith(AndroidJUnit4.class)
public class PosterRetrievalTest {

    private ImageRepository imageRepo;

    @Before
    public void setUp() {
        FirebaseAPIManager apiMgr = new FirebaseAPIManager();
        imageRepo = new ImageRepository(apiMgr);
    }

    @Test
    public void testSuccessfulPosterRetrieval() throws InterruptedException {
        // 1. Setup the "Wait" signal (Timeouts are key for Firebase)
        CountDownLatch latch = new CountDownLatch(1);
        String knownValidId = "test_poster"; // Ensure this is in your Firebase

        // 2. Execute
        imageRepo.retrieveImage(knownValidId, new FirebaseAPIManager.OnDownloadCompleteListener() {
            @Override
            public void onSuccess(String imageUrl) {
                assertNotNull("URL should not be null", imageUrl);
                assertTrue("URL should point to Firebase Storage", imageUrl.contains("firebasestorage"));
                latch.countDown(); // Signal success
            }

            @Override
            public void onFailure(String error) {
                fail("Should not have failed: " + error);
                latch.countDown();
            }
        });

        // 3. Wait for up to 10 seconds for the cloud response
        boolean completed = latch.await(10, TimeUnit.SECONDS);
        assertTrue("Test timed out - check internet connection", completed);
    }

    @Test
    public void testNonExistentPosterRetrieval() throws InterruptedException {
        CountDownLatch latch = new CountDownLatch(1);
        String fakeId = "this_poster_does_not_exist_12345";

        imageRepo.retrieveImage(fakeId, new FirebaseAPIManager.OnDownloadCompleteListener() {
            @Override
            public void onSuccess(String imageUrl) {
                fail("Should have failed for a non-existent image");
                latch.countDown();
            }

            @Override
            public void onFailure(String error) {
                // If it fails, the test passes!
                assertNotNull(error);
                latch.countDown();
            }
        });

        latch.await(10, TimeUnit.SECONDS);
    }
}