/**
 * This class generates a poster based on the event
 * It handles the logic for creating the poster and constructing it as an Bitmap
 */

package com.example.walrusevents.util;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.text.Layout;
import android.text.StaticLayout;
import android.text.TextPaint;

public class PosterGenerator {
    /**
     * Create a Poster that has the event description and QR Code
     * @param title
     * @param description: description of event
     * @param qrCode: QR code for event (said code also directs user to this poster)
     * @return: returns a bitmap of poster to be set on screen when needed (when user scans QR code)
     */
    public static Bitmap createEventPoster(String title, String description, Bitmap qrCode) {
        // Set poster specifications
        int width = 2000;
        int height = 3000;
        Bitmap poster = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(poster);
        canvas.drawColor(Color.WHITE); // Solid white background

        // Set Text type
        Paint paint = new Paint();
        paint.setColor(Color.BLACK);
        paint.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        paint.setTextAlign(Paint.Align.CENTER);

        // Center & bold title
        paint.setTextSize(160f); // Large and bold
        canvas.drawText(title, width / 2f, 300, paint);

        /**
         * This new logic was generated by Gemini 3, Google DeepMind
         * Fed in this class and asked it to make longer descriptions not run off the page
         * 12/03/26
          */
        // --- NEW DESCRIPTION LOGIC ---
        TextPaint textPaint = new TextPaint();
        textPaint.setAntiAlias(true);
        textPaint.setTextSize(70f);
        textPaint.setColor(Color.BLACK);
        textPaint.setTypeface(android.graphics.Typeface.DEFAULT);

        // Define the margins (e.g., 100 pixels from each side)
        int padding = 100;
        int textWidth = width - (padding * 2);

        // Build the StaticLayout (This handles the wrapping)
        StaticLayout staticLayout = StaticLayout.Builder.obtain(description, 0, description.length(), textPaint, textWidth)
                .setAlignment(Layout.Alignment.ALIGN_CENTER)
                .setLineSpacing(0f, 1.2f) // Adjust line spacing for readability
                .build();

        // Position the text (starting at y = 500)
        canvas.save();
        canvas.translate(padding, 500);
        staticLayout.draw(canvas);
        canvas.restore();
        // ------------------------------

        // Generate and input QR code into poster
        if (qrCode != null) {
            Bitmap largeQR = Bitmap.createScaledBitmap(qrCode, 1000, 1000, true);

            canvas.drawBitmap(largeQR, 500, 1200, null);

            // Text below QR code
            paint.setTextSize(60f);
            paint.setColor(Color.GRAY);
            canvas.drawText("SCAN TO VIEW EVENT DETAILS", width / 2f, 2400, paint);
        }

        return poster;
    }
}
