/**
 * This fragment pops up when a user wants to view the poster for an event
 * It retrieves said image from Firebase and displays it
 */

package com.example.walrusevents.ui;

import android.graphics.drawable.Drawable;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ProgressBar;

import com.bumptech.glide.Glide;
import com.bumptech.glide.load.DataSource;
import com.bumptech.glide.load.engine.GlideException;
import com.bumptech.glide.request.RequestListener;
import com.bumptech.glide.request.target.Target;
import com.example.walrusevents.R;
import com.example.walrusevents.data.FirebaseAPIManager;
import com.example.walrusevents.data.ImageRepository;



public class EventPosterFragment extends Fragment {
    private String eventId;
    private ImageRepository imageRepo;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        // This must match your XML filename: fragment_event_poster.xml
        return inflater.inflate(R.layout.fragment_event_poster, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        ImageView imageView = view.findViewById(R.id.eventPosterImage);
        ProgressBar progressBar = view.findViewById(R.id.posterProgressBar);

        // Find the back button from your RelativeLayout
        android.widget.Button backButton = view.findViewById(R.id.back_button);

        // Set the click listener to go back
        backButton.setOnClickListener(v -> {
            if (getParentFragmentManager() != null) {
                getParentFragmentManager().popBackStack();
            }
        });

        // This would be passed from the QR scan
        eventId = getArguments().getString("event_id");

        FirebaseAPIManager apiMgr = new FirebaseAPIManager();
        imageRepo = new ImageRepository(apiMgr);

        String fileName = eventId;

        /**
         * Logic related to using Glide and error handling was generated by Gemini 3, Google DeepMind
         * Fed it this file along with the goal of this fragment
         * 11/03/26
         */
        imageRepo.retrieveImage(fileName, new FirebaseAPIManager.OnDownloadCompleteListener() {
            @Override
            public void onSuccess(String imageUrl) {
                Glide.with(getContext())
                        .load(imageUrl)
                        .error(R.drawable.image_not_found_placeholder)
                        .listener(new RequestListener<Drawable>() {
                            @Override
                            public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                                progressBar.setVisibility(View.GONE);
                                return false;
                            }

                            @Override
                            public boolean onResourceReady(@NonNull Drawable resource, @NonNull Object model, Target<Drawable> target, @NonNull DataSource dataSource, boolean isFirstResource) {
                                progressBar.setVisibility(View.GONE);
                                return false;
                            }
                        })
                        .into(imageView);
            }

            @Override
            public void onFailure(String error) {
                progressBar.setVisibility(View.GONE);
                Log.e("POSTER_FRAG", "Firebase Retrieval Failed: " + error);

                // ADD THIS: If the repository fails to find the URL, show the error image!
                Glide.with(EventPosterFragment.this)
                        .load(R.drawable.image_not_found_placeholder)
                        .into(imageView);
            }
        });
    }
}