package com.example.walrusevents.model;

import java.util.Date;

/**
 * Notification class is used for formatting emails/notifications to send to differnet users
 */
public class Notification {
    private String title;
    private String message;
    private String eventId;
    private NotificationTarget targetGroup;
    private Date timestamp;

    public enum NotificationTarget {
        WAITING_LIST,
        SELECTED,
        NOT_SELECTED,
        CANCELED,
        ALL
    }

    /**
     * This function idea was generated by Gemini 3, Google DeepMind
     * Fed in the context of the notifications and asked it to fix the functionality
     * 02/04/26
     * No-argument constructor required for Firestore deserialization
     */
    public Notification() {
        this.timestamp = new Date();
    }

    /**
     * Constructor method
     * @param title header of notif
     * @param message body of notif
     * @param eventId event in discussion
     * @param targetGroup who to send it to (people in "waiting_list", "selected" or "all")
     */
    public Notification(String title, String message, String eventId, NotificationTarget targetGroup) {
        this.title = title;
        this.message = message;
        this.eventId = eventId;
        this.targetGroup = targetGroup;
        this.timestamp = new Date();
    }

    /**
     * Get title of notif
     * @return title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Change/set title of notif
     * @param title header of notif
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Get message for notif
     * @return message
     */
    public String getMessage() {
        return message;
    }

    /**
     * Change/set body of notif
     * @param message body of notif
     */
    public void setMessage(String message) { this.message = message; }

    /**
     * Get unique identifier for event
     * @return eventId
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Set id of event
     * @param eventId unique identifier for event
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * Get group we want to send notif to
     * @return targetGroup
     */
    public NotificationTarget getTargetGroup() { return targetGroup; }

    /**
     * Change/set target group
     * @param targetGroup recipient(s) notif
     */
    public void setTargetGroup(NotificationTarget targetGroup) {
        this.targetGroup = targetGroup;
    }

    /**
     * Get time at which notif was sent
     * @return timestamp
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * Set the time at which notif was sent/created
     * @param timestamp time object (long)
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public static NotificationTarget mapStatusToGroup(WaitlistEntry.Status status) {
        if (status == null) return NotificationTarget.ALL;
        switch (status) {
            case INVITED:
            case ACCEPTED: return NotificationTarget.SELECTED;
            case NOT_CHOSEN: return NotificationTarget.NOT_SELECTED;
            case PENDING: return NotificationTarget.WAITING_LIST;
            case CANCELED:
            case DECLINED:
                return NotificationTarget.CANCELED;
            default: return NotificationTarget.ALL;
        }
    }
}
