/**
 * This activity is made for displaying all notifications for the Admin
 * This was generated by Gemini 3, Google DeepMind
 * Fed in context for querying for admin
 * 06/04/26
 */
package com.example.walrusevents.activity;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

import com.example.walrusevents.R;
import com.example.walrusevents.data.NotificationRepository;
import com.example.walrusevents.model.Notification;
import com.example.walrusevents.ui.AdminAllNotificationsView;
import com.example.walrusevents.util.AdminNotificationArrayAdapter;
import java.util.List;

public class AdminAllNotificationsActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.admin_notification_log);
        AdminAllNotificationsView view = new AdminAllNotificationsView(this);
        NotificationRepository repo = new NotificationRepository();

        view.getBackButton().setOnClickListener(v -> finish());

        repo.getAllNotificationLogs(querySnapshot -> {
            List<Notification> logs = querySnapshot.toObjects(Notification.class);
            AdminNotificationArrayAdapter adapter = new AdminNotificationArrayAdapter(this, logs);
            view.getLogListView().setAdapter(adapter);
        });
    }
}
