package com.example.walrusevents.activity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.activity.EdgeToEdge;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import com.example.walrusevents.WaitlistEntry;
import com.example.walrusevents.model.Entrant;
import com.example.walrusevents.controllers.EntrantController;
import com.example.walrusevents.model.Profile;
import com.example.walrusevents.ProfileRepository;
import com.example.walrusevents.R;
import com.example.walrusevents.WaitlistRepository;
import com.example.walrusevents.model.Event;
import com.example.walrusevents.ui.AcceptInvitationFragment;
import com.example.walrusevents.util.DeviceIdManager;

/**
 * UEventDetails
 * Handles the creation and linking of classes related to viewing the details of an event
 * as a user.
 */
public class UEventDetailsActivity extends AppCompatActivity
        implements EntrantController.ActionCallback, AcceptInvitationFragment.AcceptInvitationListener {
    private Event event;
    private WaitlistEntry entry;

    //TODO: Refactor these into a view class
    private TextView event_name;
    private ImageView event_poster;
    private Button backButton;
    private Button joinButton;
    private Button seePoolButton;
    private WaitlistRepository waitlistRepository;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.event_details);

        waitlistRepository = new WaitlistRepository();
        /*
        * Retrieve Event object that was clicked in MainActivity
        * Exception handling referenced from https://www.geeksforgeeks.org/android/exceptions-in-android-with-example/. March 12, 2026
         */
        try {
            event = getIntent().getSerializableExtra("Event", Event.class);
            if (event == null) { /* If event doesn't load, return to main activity */
                throw new NullPointerException("Selected Event not found");
            }
        } catch (NullPointerException e) {
            Log.e("Event Details", "Missing Object", e);
        }

        /*
        * Display selected event information
         */
        event_name = findViewById(R.id.event_name);
        event_name.setText(event.getTitle());

        // TODO: add images
        event_poster = findViewById(R.id.event_poster);

        /**
         * This block was generated by Gemini 3, Google DeepMind
         * Fed this class and the requirement that the poster needs to be retrived and displayed here
         * 13/03/26
         */
        // Inside onCreate, after event_poster = findViewById(R.id.event_poster);

        if (event != null) {
            String eventId = event.getEventId();

            // 1. Initialize the API Manager and Repository
            com.example.walrusevents.data.FirebaseAPIManager apiMgr = new com.example.walrusevents.data.FirebaseAPIManager();
            com.example.walrusevents.data.ImageRepository imageRepo = new com.example.walrusevents.data.ImageRepository(apiMgr);

            // 2. Fetch the image URL and load it with Glide
            imageRepo.retrieveImage(eventId, new com.example.walrusevents.data.FirebaseAPIManager.OnDownloadCompleteListener() {
                @Override
                public void onSuccess(String imageUrl) {
                    // Glide handles the background download and UI update
                    com.bumptech.glide.Glide.with(UEventDetailsActivity.this)
                            .load(imageUrl)
                            .placeholder(R.drawable.rounded_light_blue_square) // Shown while loading
                            .error(R.drawable.image_not_found_placeholder)   // Shown if retrieval fails
                            .into(event_poster);
                }

                @Override
                public void onFailure(String error) {
                    Log.e("POSTER_LOAD", "User view could not find poster: " + error);
                    // Optional: Set a default "no image" placeholder
                    event_poster.setImageResource(R.drawable.image_not_found_placeholder);
                }
            });
        }

        event_poster.setOnClickListener(v -> {
            com.example.walrusevents.ui.EventPosterFragment posterFragment = new com.example.walrusevents.ui.EventPosterFragment();
            Bundle args = new Bundle();
            args.putString("event_id", event.getEventId());
            posterFragment.setArguments(args);

            getSupportFragmentManager().beginTransaction()
                    .add(android.R.id.content, posterFragment)
                    .addToBackStack(null)
                    .commit();
        });
// ------>

        TextView event_details = findViewById(R.id.Event_Details);
        String desc = event.getDescription();
        if(!desc.isEmpty()) {
            event_details.setText(desc);
        }

        /*
        * Set 'Back' button to return to MainActivity
         */
        backButton = findViewById(R.id.back_button);
        backButton.setOnClickListener(v -> {
            finish();
        });

        /*
        * Set seePoolButton to go to OEventPoolActivity
         */
        seePoolButton = findViewById(R.id.see_pool_button);
        seePoolButton.setOnClickListener(v -> {
            Intent seePool = new Intent(UEventDetailsActivity.this, UViewWaitlistActivity.class);
            seePool.putExtra("Event", event);
            startActivity(seePool);
        });

        // Test Entrant. TODO: Implement full profile function
        String deviceId = DeviceIdManager.getOrCreate(this);
        Entrant me = new Entrant(new Profile(deviceId,"placeholderName","placeholderEmail"));

        /*
        * Set joinButton to submit an Entrant to the Waitlist
         */
        joinButton = findViewById(R.id.join_event_button);
        joinButton.setOnClickListener(v -> {
            WaitlistRepository waitRep = new WaitlistRepository();
            ProfileRepository pfRep = new ProfileRepository();
            EntrantController entrantController = new EntrantController(me, waitRep, pfRep);
            entrantController.joinWaitlist(event.getEventId(), this);
        });

        checkForInvitation();
    }

    private void checkForInvitation() {
        if (!event.isInConfirmation()) {
            return;
        }

        String deviceId = DeviceIdManager.getOrCreate(this);
        String eventId = event.getEventId();

        waitlistRepository.getEntry(eventId, deviceId, new WaitlistRepository.EntryCallback() {
            @Override
            public void onEntryLoaded(WaitlistEntry entry) {
                if (entry != null) {
                    AcceptInvitationFragment inviteFragment = new AcceptInvitationFragment();
                    switch (entry.getStatus()) {
                        case INVITED:
                            inviteFragment =
                                    AcceptInvitationFragment.newInstance(UEventDetailsActivity.this, true);
                            inviteFragment.show(getSupportFragmentManager(), "Invited");
                            break;
                        case PENDING:
                            inviteFragment =
                                    AcceptInvitationFragment.newInstance(UEventDetailsActivity.this, false);
                            inviteFragment.show(getSupportFragmentManager(), "Not Invited");
                            break;
                        default:
                            break;
                    }
                    UEventDetailsActivity.this.entry = entry;
                }
            }
        });
    }

    @Override
    public void onSuccess() {

    }

    @Override
    public void onFailure(String errorMessage) {
        System.err.println(errorMessage);
    }

    @Override
    public void acceptInvite() {
        entry.setStatus(WaitlistEntry.Status.ACCEPTED);
        waitlistRepository.updateStatus(entry.getEventId(), entry.getEntrantId(), WaitlistEntry.Status.ACCEPTED,
                new WaitlistRepository.SaveCallback() {
            @Override
            public void onSuccess() {

            }

            @Override
            public void onFailure(String error) {
                System.err.println(error);
            }
        });
    }

    @Override
    public void declineInvite() {
        entry.setStatus(WaitlistEntry.Status.DECLINED);
        waitlistRepository.updateStatus(entry.getEventId(), entry.getEntrantId(), WaitlistEntry.Status.DECLINED,
                new WaitlistRepository.SaveCallback() {
                    @Override
                    public void onSuccess() {

                    }

                    @Override
                    public void onFailure(String error) {
                        System.err.println(error);
                    }
                });
    }
}