package com.example.walrusevents.activity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import com.example.walrusevents.EventRepository;
import com.example.walrusevents.WaitlistEntry;
import com.example.walrusevents.model.Entrant;
import com.example.walrusevents.controllers.EntrantController;
import com.example.walrusevents.model.Profile;
import com.example.walrusevents.ProfileRepository;
import com.example.walrusevents.R;
import com.example.walrusevents.WaitlistRepository;
import com.example.walrusevents.model.Event;
import com.example.walrusevents.ui.AcceptInvitationFragment;
import com.example.walrusevents.util.DeviceIdManager;
import com.example.walrusevents.data.FirebaseAPIManager;
import com.example.walrusevents.data.ImageRepository;
import com.example.walrusevents.ui.EventPosterFragment;
import com.google.firebase.Firebase;

/**
 * UEventDetails
 * Handles the creation and linking of classes related to viewing the details of an event
 * as a user.
 */
public class UEventDetailsActivity extends AppCompatActivity
        implements EntrantController.ActionCallback, AcceptInvitationFragment.AcceptInvitationListener {
    private Event event;
    private WaitlistEntry entry;

    //TODO: Refactor these into a view class
    private TextView event_name;
    private ImageView event_poster;
    private Button backButton;
    private Button joinButton;
    private Button seePoolButton;
    private WaitlistRepository waitlistRepository;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.event_details);

        waitlistRepository = new WaitlistRepository();
        /**
         * This block was generated by Gemini 3, Google DeepMind
         * Fed this class and the requirement that the event needs to be retrived and displayed here
         * 26/03/26
         */
        String scannedId = getIntent().getStringExtra("EVENT_ID");

        if (scannedId != null) {
            // PATH 1: Arrived from QR Scanner
            // We only have the ID string, so we must fetch the data from Firebase
            fetchEventFromFirestore(scannedId);
        } else {
            // PATH 2: Arrived from clicking the ListView
            try {
                event = getIntent().getSerializableExtra("Event", Event.class);
                if (event != null) {
                    setupUI(); // Initialize the screen once the object is ready
                } else {
                    Log.e("Event Details", "Event object is null");
                    finish();
                }
            } catch (Exception e) {
                Log.e("Event Details", "Error loading event", e);
                finish();
            }
        }
    }

    private void checkForInvitation() {
        if (event == null || !event.isInConfirmation()) {
            return;
        }

        String deviceId = DeviceIdManager.getOrCreate(this);
        String eventId = event.getEventId();

        waitlistRepository.getEntry(eventId, deviceId, new WaitlistRepository.EntryCallback() {
            @Override
            public void onEntryLoaded(WaitlistEntry entry) {
                if (entry != null) {
                    AcceptInvitationFragment inviteFragment;
                    switch (entry.getStatus()) {
                        case INVITED:
                            inviteFragment =
                                    AcceptInvitationFragment.newInstance(UEventDetailsActivity.this, true);
                            inviteFragment.show(getSupportFragmentManager(), "Invited");
                            break;
                        case PENDING:
                            inviteFragment =
                                    AcceptInvitationFragment.newInstance(UEventDetailsActivity.this, false);
                            inviteFragment.show(getSupportFragmentManager(), "Not Invited");
                            break;
                        default:
                            break;
                    }
                    UEventDetailsActivity.this.entry = entry;
                }
            }
        });
    }

    @Override
    public void onSuccess() {

    }

    @Override
    public void onFailure(String errorMessage) {
        System.err.println(errorMessage);
    }

    @Override
    public void acceptInvite() {
        if (entry == null) return;
        entry.setStatus(WaitlistEntry.Status.ACCEPTED);
        waitlistRepository.updateStatus(entry.getEventId(), entry.getEntrantId(), WaitlistEntry.Status.ACCEPTED,
                new WaitlistRepository.SaveCallback() {
            @Override
            public void onSuccess() {

            }

            @Override
            public void onFailure(String error) {
                System.err.println(error);
            }
        });
    }

    @Override
    public void declineInvite() {
        if (entry == null) return;
        entry.setStatus(WaitlistEntry.Status.DECLINED);
        waitlistRepository.updateStatus(entry.getEventId(), entry.getEntrantId(), WaitlistEntry.Status.DECLINED,
                new WaitlistRepository.SaveCallback() {
                    @Override
                    public void onSuccess() {

                    }

                    @Override
                    public void onFailure(String error) {
                        System.err.println(error);
                    }
                });
    }

    /**
     * This function was generated by Gemini 3, Google DeepMind
     * was a consequence of the onCreate restructuring
     * Uses your existing EventRepository to get the full object from Firestore.
     */
    private void fetchEventFromFirestore(String eventId) {
        EventRepository repo = new EventRepository();
        repo.getEvent(eventId, new EventRepository.EventCallback() {
            @Override
            public void onEventLoaded(Event loadedEvent) {
                if (loadedEvent != null) {
                    event = loadedEvent;
                    setupUI(); // Now that we have the object, we can fill the TextViews
                } else {
                    Toast.makeText(UEventDetailsActivity.this, "Invalid QR Code or Event not found", Toast.LENGTH_SHORT).show();
                    finish();
                }
            }
        });
    }

    /**
     * Move your UI setting logic (TextViews, Glide, Buttons) into this method
     * so it works for both scan and click results.
     */
    private void setupUI() {
        if (event == null) return;

        event_name = findViewById(R.id.event_name);
        event_name.setText(event.getTitle());

        event_poster = findViewById(R.id.event_poster);

        FirebaseAPIManager apiMgr = new FirebaseAPIManager();
        ImageRepository imageRepo = new ImageRepository(apiMgr);

        // Get image from Firebase
        imageRepo.retrieveImage(event.getEventId(), new com.example.walrusevents.data.FirebaseAPIManager.OnDownloadCompleteListener() {
            @Override
            public void onSuccess(String imageUrl) {
                com.bumptech.glide.Glide.with(UEventDetailsActivity.this)
                        .load(imageUrl)
                        .placeholder(R.drawable.rounded_light_blue_square)
                        .error(R.drawable.image_not_found_placeholder)
                        .into(event_poster);
            }

            @Override
            public void onFailure(String error) {
                event_poster.setImageResource(R.drawable.image_not_found_placeholder);
            }
        });

        TextView event_details = findViewById(R.id.Event_Details);
        event_details.setText(event.getDescription());

        // Take user to poster fragment if they click on poster
        event_poster.setOnClickListener(v -> {
            EventPosterFragment posterFragment = new EventPosterFragment();
            Bundle args = new Bundle();
            args.putString("event_id", event.getEventId());
            posterFragment.setArguments(args);

            getSupportFragmentManager().beginTransaction()
                    .add(android.R.id.content, posterFragment)
                    .addToBackStack(null)
                    .commit();
        });

        /*
         * Set 'Back' button to return to MainActivity
         */
        backButton = findViewById(R.id.back_button);
        backButton.setOnClickListener(v -> {
            finish();
        });

        /*
         * Set seePoolButton to go to OEventPoolActivity
         */
        seePoolButton = findViewById(R.id.see_pool_button);
        seePoolButton.setOnClickListener(v -> {
            Intent seePool = new Intent(UEventDetailsActivity.this, UViewWaitlistActivity.class);
            seePool.putExtra("Event", event);
            startActivity(seePool);
        });

        // Test Entrant. TODO: Implement full profile function
        String deviceId = DeviceIdManager.getOrCreate(this);
        Entrant me = new Entrant(new Profile(deviceId,"placeholderName","placeholderEmail"));

        /*
         * Set joinButton to submit an Entrant to the Waitlist
         */
        joinButton = findViewById(R.id.join_event_button);
        joinButton.setOnClickListener(v -> {
            WaitlistRepository waitRep = new WaitlistRepository();
            ProfileRepository pfRep = new ProfileRepository();
            EntrantController entrantController = new EntrantController(me, waitRep, pfRep);
            entrantController.joinWaitlist(event.getEventId(), this);
        });

        checkForInvitation();
    }
}