plugins {
    alias(libs.plugins.android.application)

    // add the google services gradle plugin
    id("com.google.gms.google-services")

}

android {
    namespace = "com.example.walrusevents"
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId = "com.example.walrusevents"
        minSdk = 35
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.activity)
    implementation(libs.constraintlayout)
    implementation(libs.firebase.firestore)
    implementation(libs.fragment.testing)
    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
    // Firestore dependency
    implementation("com.google.firebase:firebase-storage:20.3.0")

    // Import the Firebase BoM
    implementation(platform("com.google.firebase:firebase-bom:34.10.0"))


    // Given by Firebase during initialization
    // TODO: Add the dependencies for Firebase products you want to use
    // When using the BoM, don't specify versions in Firebase dependencies
    implementation("com.google.firebase:firebase-analytics")


    // Add the dependencies for any other desired Firebase products
    // https://firebase.google.com/docs/android/setup#available-libraries


    // Dependencies for ZXing (used for generating QR codes)
    // Code and logic for QR code were taken from a Reintech article provided by our TA
    // https://reintech.io/blog/implementing-android-app-qr-code-scanner
    implementation("com.journeyapps:zxing-android-embedded:4.3.0")
    implementation("com.google.zxing:core:3.5.3")
    // Required for camera functionality
    implementation("androidx.appcompat:appcompat:1.6.1")

    // Dependencies for Glide (used for converting a URI into a Bitmap
    implementation("com.github.bumptech.glide:glide:4.16.0")
    // This 'annotationProcessor' line is what makes Glide smart
    annotationProcessor("com.github.bumptech.glide:compiler:4.16.0")

    // UI Testing
    // ... your other implementation lines (Firebase, Glide, etc.) ...

    // UI Testing - Keep these consolidated
    /**
     * UI related dependencies and configs section was generated by Gemini 3, Google DeepMind
     * Fed an error message I was getting about espresso which caused my UI tests to not run
     * 11/03/26
     */
    debugImplementation("androidx.fragment:fragment-testing:1.8.5") // Updated

    testImplementation("junit:junit:4.13.2")

    // Updated Testing Suite to match modern SDKs
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
    androidTestImplementation("androidx.test:runner:1.6.2")
    androidTestImplementation("androidx.test:rules:1.6.1")
    // ADD THIS LINE for Intent recognition (Intents.init, intended, etc.)
    androidTestImplementation("androidx.test.espresso:espresso-intents:3.6.1")

    // Recommended for ActivityScenarioRule
    androidTestImplementation("androidx.test:rules:1.6.1")
}


configurations.all {
    resolutionStrategy {
        // Updated versions to fix the ReflectiveMethod error
        force("androidx.test:monitor:1.7.2")
        force("androidx.test:core:1.6.1")
        force("androidx.test:runner:1.6.2")
    }
}