package com.example.walrusevents.data;

import android.net.Uri;
import android.util.Log;

import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.storage.FirebaseStorage;
import com.google.firebase.storage.StorageReference;

public class FirebaseAPIManager {

    /**
    * This class controls the logic related to the external DB through APIs
    * Will talk to the image service and liaison this information to the app through ImageRepository
    * Done to keep the logic of the app separate
    * This planning was made by Gemini 3, Google DeepMind
    * Was given a description of tasks related to image management
    * 03/03/26
    *
    * @return
    */
    private final StorageReference storageReference;

    public FirebaseAPIManager() {
        // Initialize Firebase Storage (for files/images)
        FirebaseStorage storage = FirebaseStorage.getInstance();
        this.storageReference = storage.getReference();  // Point to root of DB
    }

    public void uploadImage(Uri fileUri, String fileName, OnUploadCompleteListener listener) {
        StorageReference fileRef = storageReference.child("images/" + fileName);

        fileRef.putFile(fileUri)
                .addOnSuccessListener(taskSnapshot -> {
                    Log.d("FirebaseAPI", "Upload was successful: " + fileName);
                    listener.onSuccess();
                })
                .addOnFailureListener(e -> {
                    // The following lines were generated by Gemini 3, Google DeepMind
                    // The logic behind this method was fed
                    // 04/03/26
                    Log.e("FirebaseAPI", "Upload failed for " + fileName + ": " + e.getMessage());
                    listener.onFailure(e.getMessage());
                });
    }

    /**
     * The following function was generated by Gemini 3, Google DeepMind
     * Information about the database class requirements and plans to use Firebase was fed
     * 04/03/26
     * In Firebase, downloading usually means getting the URL string.
     * Because this is an async network call, we use a listener instead of a direct 'return'.
     */
    public void downloadImage(String fileName, OnDownloadCompleteListener listener) {
        StorageReference fileRef = storageReference.child("images/" + fileName);

        fileRef.getDownloadUrl()
                .addOnSuccessListener(uri -> {
                    // Success! Return the URL string
                    listener.onSuccess(uri.toString());
                })
                .addOnFailureListener(e -> {
                    // Miss! Handle the error
                    listener.onFailure(e.getMessage());
                });
    }

    // Interfaces for communication back to the Repository
    public interface OnUploadCompleteListener {
        void onSuccess();
        void onFailure(String error);
    }

    public interface OnDownloadCompleteListener {
        void onSuccess(String imageUrl);
        void onFailure(String error);
    }
}